### ISSUE TITLE
Android error: package com.microsoft.appcenter.reactnative.appcenter does not exist

### ISSUE THREAD

**Issue by pcooney10** [Microsoft/AppCenter-SDK-React-Native#343]
### **Description**

Android is unable to find the following imports after following the installation instructions. Working fine on iOS:
```
import com.microsoft.appcenter.reactnative.crashes.AppCenterReactNativeCrashesPackage;
import com.microsoft.appcenter.reactnative.analytics.AppCenterReactNativeAnalyticsPackage;
import com.microsoft.appcenter.reactnative.appcenter.AppCenterReactNativePackage;
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. yarn add appcenter appcenter-analytics appcenter-crashes
2. react-native link appcenter 
3. react-native link appcenter-analytics 
4. react-native link appcenter-crashes
5. Build in Android Studio

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

error: package com.microsoft.appcenter.reactnative.crashes does not exist
error: package com.microsoft.appcenter.reactnative.analytics does not exist
error: package com.microsoft.appcenter.reactnative.appcenter does not exist
error: cannot find symbol new AppCenterReactNativeCrashesPackage(MainApplication.this, getResources().getString(R.string.appCenterCrashes_whenToSendCrashes)),
error: cannot find symbol new AppCenterReactNativeAnalyticsPackage(MainApplication.this, getResources().getString(R.string.appCenterAnalytics_whenToEnableAnalytics)),
error: cannot find symbol new AppCenterReactNativePackage(MainApplication.this)
```

I have this running fine on iOS, but Android can't seem to find the appcenter packages for some reason. In the example I saw this line:
```
maven {
    url  'https://dl.bintray.com/vsappcenter/appcenter-snapshot'
}
```
Do I need to put this in our apps? I tried and it didn't seem to have any effect.

### **Details**

1. Which SDK version are you using?
    - `1.60` 

2. Which OS version did you experience the issue on?
    - `Android 6.0 Marshmallow`

3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - `Google Pixel 2 emulator`

4. What third party libraries are you using?
    - `react-native-maps`, `react-native-google-signin`, `react-navigation`

5. Run the following command and paste the output below: `react-native info`
```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.7.0
  Yarn: 1.7.0
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```
6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

    - `n/a`

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:

    - `n/a, cannot build the app`

**Comment by pcooney10** [comment]
Also potentially related, I am getting the following error during the gradle sync process (only after adding appcenter):
`Cannot call getBootClasspath() before setTargetInfo() is called.`

I am using `'com.android.tools.build:gradle:3.0.1'`.

**Comment by pcooney10** [comment]
I have also followed the instructions [here (#240)](https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/240#issuecomment-366299382), but to no avail.

**Comment by clpolet** [comment]
Hi @pcooney10 

Thanks for contacting us.
The default integration steps from [React Native ](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native) should have worked. The `https://dl.bintray.com/vsappcenter/appcenter-snapshot` url is for the snapshot versions of the AC Android native SDK it's not the released ones. So you don't need this line.

What's causing the issue is not really clear yet, I saw your are using Gradle v3.0.1, you may want to try with Gradle v2.3.3 which seems to be the version used by [React Native on their repository](https://github.com/facebook/react-native/blob/18e9ea211296d2ce553d3fb37411f18e31d00181/build.gradle#L16) .

**Comment by pcooney10** [comment]
Ok, thank you for your reply @clpolet. So does this not work with gradle `3.0.0+`?

**Comment by bmourat** [comment]
@pcooney10 
I can confirm that this works with android gradle plugin `3.0.0+`. So this must be specific setup of your project. Could you please share, if it is possible, build.gradle files for the project and app, and also settings.gradle?

**Comment by pcooney10** [comment]
Ok. And sure:

```java
// build.gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:4.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven { 
            url 'https://jitpack.io'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
    }
}
```

```java
// app/build.gradle
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

apply plugin: 'com.android.application'

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: '../../node_modules/react-native/react.gradle'` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: 'index.android.bundle',
 *
 *   // the entry file for bundle generation
 *   entryFile: 'index.android.js',
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where 'package.json' lives
 *   root: '../../',
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: '$buildDir/intermediates/assets/debug',
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: '$buildDir/intermediates/assets/release',
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: '$buildDir/intermediates/res/merged/debug',
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: '$buildDir/intermediates/res/merged/release',
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ['android/**', 'ios/**'],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ['node'],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: 'index.js'
]

apply from: '../../node_modules/react-native/react.gradle'
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"  

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    defaultConfig {
        applicationId 'com.myCompany.myApp'
        minSdkVersion 16
        targetSdkVersion 23
        renderscriptTargetApi 23
        renderscriptSupportModeEnabled true
        versionCode 1
        versionName '1.0'
        multiDexEnabled true
        ndk {
            abiFilters 'armeabi-v7a', 'x86'
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include 'armeabi-v7a', 'x86'
        }
    }
    buildTypes {
        debug {
            // Note: CodePush updates should not be tested in Debug mode as they are overriden by the RN packager. However, because CodePush checks for updates in all modes, we must supply a key.
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
        releaseStaging {
            matchingFallbacks = ['release', 'debug']
            buildConfigField "String", "CODEPUSH_KEY", '"myWorkingCodePushKey"'
        }
        release {
            buildConfigField "String", "CODEPUSH_KEY", '"myOtherWorkingCodePushKey"'
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ['armeabi-v7a':1, 'x86':2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    configurations.all {
        resolutionStrategy {
            force 'com.airbnb.android:lottie:2.5.5'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.0.2'
    implementation 'com.facebook.react:react-native:+'  // from node_modules
    implementation project(':react-native-linear-gradient')
    implementation project(':lottie-react-native')
    implementation project(':react-native-onesignal')
    implementation project(':react-native-branch')
    implementation project(':react-native-blur')
    implementation project(':react-native-analytics-segment-io')
    implementation project(':react-native-fast-image')
    implementation project(':react-native-device-info')
    implementation project(':react-native-image-picker')
    implementation(project(':react-native-google-signin')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-auth'
    }
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation project(':react-native-fbsdk')
    implementation project(':react-native-custom-tabs')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-svg')
    implementation project(':react-native-rate')
    implementation project(':react-native-google-analytics-bridge')
    implementation project(':react-native-code-push')
    implementation project(':appcenter')
    implementation project(':appcenter-analytics')
    implementation project(':appcenter-crashes')
    implementation 'com.segment.analytics.android:analytics:4.3.1'
    implementation 'com.segment.analytics.android.integrations:mixpanel:2.0.0'
    implementation 'com.segment.analytics.android.integrations:flurry:3.0.0'
    implementation('com.onesignal:OneSignal:[3.9.1, 3.99.99]'){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-gcm'
        exclude group: 'com.google.android.gms', module: 'play-services-analytics'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    implementation('com.google.android.gms:play-services-base:11.8.0'){
        force = true
    }
    implementation('com.google.android.gms:play-services-maps:11.8.0'){
        force = true
    }
    implementation('com.google.android.gms:play-services-auth:11.8.0'){
        force = true
    }
    implementation('com.google.android.gms:play-services-gcm:11.8.0'){
        force = true
    }
    implementation('com.google.android.gms:play-services-analytics:11.8.0'){
        force = true
    }
    implementation('com.google.android.gms:play-services-location:11.8.0'){
        force = true
    }
}

// adding per the instructions of react-native-google-signin
apply plugin: 'com.google.gms.google-services'

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

```


```java
// settings.gradle
rootProject.name = 'myApp'

include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')

include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')

include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')

include ':react-native-onesignal'
project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android')

include ':react-native-branch'
project(':react-native-branch').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-branch/android')

include ':react-native-blur'
project(':react-native-blur').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-blur/android')

include ':react-native-analytics-segment-io'
project(':react-native-analytics-segment-io').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-analytics-segment-io/android')

include ':react-native-fast-image'
project(':react-native-fast-image').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fast-image/android')

include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')

include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')

include ':react-native-fbsdk'
project(':react-native-fbsdk').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbsdk/android')

include ':react-native-google-signin'
project(':react-native-google-signin').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-google-signin/android')

include ':react-native-custom-tabs'
project(':react-native-custom-tabs').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-custom-tabs/android')

include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')

include ':react-native-svg'
project(':react-native-svg').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-svg/android')

include ':react-native-rate'
project(':react-native-rate').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-rate/android')

include ':react-native-google-analytics-bridge'
project(':react-native-google-analytics-bridge').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-google-analytics-bridge/android')

include ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')

include ':appcenter'
project(':appcenter').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter/android')

include ':appcenter-crashes'
project(':appcenter-crashes').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter-crashes/android')

include ':appcenter-analytics'
project(':appcenter-analytics').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter-analytics/android')

include ':app'
```

```java
// MainApplication.java
package com.myCompany.myApp;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.microsoft.codepush.react.CodePush;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;

import com.BV.LinearGradient.LinearGradientPackage;
import com.airbnb.android.react.lottie.LottiePackage;
import com.airbnb.android.react.maps.MapsPackage;
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
import io.branch.rnbranch.RNBranchPackage;
import io.branch.referral.Branch;
import com.cmcewen.blurview.BlurViewPackage;
import com.leo_pharma.analytics.AnalyticsPackage;
import com.dylanvann.fastimage.FastImageViewPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;
import com.imagepicker.ImagePickerPackage;
import co.apptailor.googlesignin.RNGoogleSigninPackage;
import com.github.droibit.android.reactnative.customtabs.CustomTabsPackage;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import com.horcrux.svg.SvgPackage;
import com.RNRate.RNRatePackage;
import com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridgePackage;
import com.microsoft.appcenter.reactnative.appcenter.AppCenterReactNativePackage;
import com.microsoft.appcenter.reactnative.crashes.AppCenterReactNativeCrashesPackage;
import com.microsoft.appcenter.reactnative.analytics.AppCenterReactNativeAnalyticsPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }
    
    
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new LinearGradientPackage(),
        new LottiePackage(),
        new MapsPackage(),
        new ReactNativeOneSignalPackage(),
        new RNBranchPackage(),
        new BlurViewPackage(),
        new AnalyticsPackage(),
        new FastImageViewPackage(),
        new RNDeviceInfo(),
        new ImagePickerPackage(),
        new FBSDKPackage(mCallbackManager),
        new RNGoogleSigninPackage(),
        new CustomTabsPackage(),
        new RNGestureHandlerPackage(),
        new SvgPackage(),
        new RNRatePackage(),
        new GoogleAnalyticsBridgePackage(),
        new CodePush(BuildConfig.CODEPUSH_KEY, getApplicationContext(), BuildConfig.DEBUG, R.string.CodePushPublicKey),
        new AppCenterReactNativeCrashesPackage(MainApplication.this, getResources().getString(R.string.appCenterCrashes_whenToSendCrashes)),
        new AppCenterReactNativeAnalyticsPackage(MainApplication.this, getResources().getString(R.string.appCenterAnalytics_whenToEnableAnalytics)),
        new AppCenterReactNativePackage(MainApplication.this)
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    Branch.getAutoInstance(this);
  }
}

```

**Comment by pcooney10** [comment]
After some playing around (namely downgrading to gradle `2.3.3`), I was prompted to install a few things along the way in the build process (Android NDK, and some previous versions of the Android SDK Build Tools). I obviously also did a few Build>Clean Project and nuked the `/build` directory of the android project a few times, but I had been doing this when initially debugging the issue on `3.0.1`. 

Eventually, I saw this in my Gradle Sync logs:

CONFIGURE SUCCESSFUL in 2s
Download https://jcenter.bintray.com/com/microsoft/appcenter/reactnative/appcenter-react-native/1.6.0/appcenter-react-native-1.6.0-sources.jar
Download https://jcenter.bintray.com/com/microsoft/appcenter/appcenter-analytics/1.6.1/appcenter-analytics-1.6.1-sources.jar
Download https://jcenter.bintray.com/com/microsoft/appcenter/appcenter-crashes/1.6.1/appcenter-crashes-1.6.1-sources.jar
Download https://jcenter.bintray.com/com/microsoft/appcenter/appcenter/1.6.1/appcenter-1.6.1-sources.jar


Maybe something changed on MS's end? Or the bug in my app was crashing things before it got to this step? Still a bit confused as to what happened, but would like to figure out. Glad it's working though :)

**Comment by sajaddp** [comment]
I have the same problem.
My solution was similar to @pcooney10 's last comment and the problem was fixed, Is there any easier way?
```
Environment:
  OS: Windows 10
  Node: 10.5.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4
```

**Comment by clpolet** [comment]
@pcooney10 glad you fixed your issue. We couldn't reproduce, so unfortunately the cause of the issue remains mysterious. Seems like some cleanup did the trick, it would be strange that the Gradle version had something to do with it since @bmourat was able to get it working with Gradle 3.0.0+ but he might not have the same setup. It could be a mix of app setup + Gradle + clean up. I'll go ahead and close the issue for now.

**Comment by adirzoari** [comment]
@pcooney10  @clpolet  @sajaddp I have same issue. what to do? to download from links and where to install\put them?

**Comment by Surbhiairan** [comment]
@clpolet @bmourat I am still having this issue. Where are we suppose to put the jar files?

**Comment by guperrot** [comment]
Hi @adirzoari and @Surbhiairan, please create separate issues using the github template as each case might be different and we need details about your individual setups and the exact description of the problem.

Thanks in advance.
