### ISSUE TITLE
Enabling Crashes triggers the "new NativeEventEmitter()" warning

### ISSUE THREAD

**Issue by nkoudelia** [microsoft/appcenter-sdk-react-native#941]
### **Description**

Calling `await Crashes.setEnabled(true)` or `await Crashes.setEnabled(false)` results in the following warnings:

```
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

### **Repro Steps**

1. Call the following method upon app initialization:

```TypeScript
import Crashes from 'appcenter-crashes';

await Crashes.setEnabled(true);
```

### **Details**

1. Which version of the App Center SDK are you using?
    - 4.3.0
2. Which OS version did you experience the issue on?
    - Android 7.1.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Nexus 6 API 25 emulator
4. Run the following command and paste the output below: `react-native info`
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 16.15 GB / 31.72 GB
  Binaries:
    Node: 14.17.6 - C:\Users\NIKOLA~1\AppData\Local\Temp\yarn--1637746400809-0.6760770554158648\node.CMD
    Yarn: 1.22.15 - C:\Users\NIKOLA~1\AppData\Local\Temp\yarn--1637746400809-0.6760770554158648\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-25 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_302 - C:\Program Files\OpenJDK\openjdk-8u302-b08\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.x => 17.0.2
    react-native: 0.66.x => 0.66.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
Done in 3.70s.
```

**Comment by aleksandr-dorofeev** [comment]
Hi, @nkoudelia 
Thanks for getting in touch with us!
Could you please share a code snippet of how and where you start App Center?
Also could you please share [verbose](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/react-native#adjust-the-log-level) logs, to better understand this behavior?

**Comment by nkoudelia** [comment]
Hi @aleksandr-dorofeev
Please see the startup code [here](https://github.com/nkoudelia/AwesomeTSProject/blob/main/App.tsx#L67).

The logs are below:

```
2021-11-24 18:10:23.033 4365-4365/? I/art: Late-enabling -Xcheck:jni
2021-11-24 18:10:23.033 4365-4365/? I/art: Late-enabling -Xcheck:jni
2021-11-24 18:10:23.033 4365-4365/? I/art: Late-enabling -Xcheck:jni
2021-11-24 18:10:23.033 4365-4365/? W/art: Unexpected CPU variant for X86 using defaults: x86
2021-11-24 18:10:23.033 4365-4365/? W/art: Unexpected CPU variant for X86 using defaults: x86
2021-11-24 18:10:23.033 4365-4365/? W/art: Unexpected CPU variant for X86 using defaults: x86
2021-11-24 18:10:23.105 4365-4365/com.awesometsproject D/SoLoader: init start
2021-11-24 18:10:23.105 4365-4365/com.awesometsproject D/SoLoader: adding system library source: /vendor/lib
2021-11-24 18:10:23.105 4365-4365/com.awesometsproject D/SoLoader: adding system library source: /system/lib
2021-11-24 18:10:23.105 4365-4365/com.awesometsproject D/SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.awesometsproject-1/lib/x86 flags = 0]
2021-11-24 18:10:23.105 4365-4365/com.awesometsproject D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.awesometsproject/lib-main flags = 1]
2021-11-24 18:10:23.105 4365-4365/com.awesometsproject D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
2021-11-24 18:10:23.105 4365-4365/com.awesometsproject D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/vendor/lib flags = 2]
2021-11-24 18:10:23.105 4365-4365/com.awesometsproject D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.awesometsproject-1/lib/x86 flags = 0]
2021-11-24 18:10:23.105 4365-4365/com.awesometsproject D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.awesometsproject/lib-main flags = 1]
2021-11-24 18:10:23.106 4365-4365/com.awesometsproject V/fb-UnpackingSoSource: locked dso store /data/user/0/com.awesometsproject/lib-main
2021-11-24 18:10:23.106 4365-4365/com.awesometsproject I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.awesometsproject/lib-main
2021-11-24 18:10:23.106 4365-4365/com.awesometsproject V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.awesometsproject/lib-main
2021-11-24 18:10:23.106 4365-4365/com.awesometsproject D/SoLoader: init finish: 4 SO sources prepared
2021-11-24 18:10:23.106 4365-4365/com.awesometsproject D/SoLoader: init exiting
2021-11-24 18:10:23.122 4365-4365/com.awesometsproject D/AppCenterCrashes: Creating crashes module with crashListener DO_NOT_ASK_JAVASCRIPT
2021-11-24 18:10:23.132 4365-4365/com.awesometsproject D/SoLoader: init exiting
2021-11-24 18:10:23.133 4365-4365/com.awesometsproject D/SoLoader: About to load: libjscexecutor.so
2021-11-24 18:10:23.133 4365-4365/com.awesometsproject D/SoLoader: libjscexecutor.so not found on /data/data/com.awesometsproject/lib-main
2021-11-24 18:10:23.133 4365-4365/com.awesometsproject D/SoLoader: libjscexecutor.so found on /data/app/com.awesometsproject-1/lib/x86
2021-11-24 18:10:23.133 4365-4365/com.awesometsproject D/SoLoader: Not resolving dependencies for libjscexecutor.so
2021-11-24 18:10:23.153 4365-4365/com.awesometsproject D/JavaScriptCore.Version: 250230.2.1
2021-11-24 18:10:23.153 4365-4365/com.awesometsproject D/SoLoader: Loaded: libjscexecutor.so
2021-11-24 18:10:23.153 4365-4365/com.awesometsproject D/SoLoader: init exiting
2021-11-24 18:10:23.188 4365-4365/com.awesometsproject D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-11-24 18:10:23.205 4365-4388/com.awesometsproject D/SoLoader: About to load: libfbjni.so
2021-11-24 18:10:23.205 4365-4388/com.awesometsproject D/SoLoader: libfbjni.so not found on /data/data/com.awesometsproject/lib-main
2021-11-24 18:10:23.205 4365-4388/com.awesometsproject D/SoLoader: libfbjni.so found on /data/app/com.awesometsproject-1/lib/x86
2021-11-24 18:10:23.205 4365-4388/com.awesometsproject D/SoLoader: Not resolving dependencies for libfbjni.so
2021-11-24 18:10:23.206 4365-4388/com.awesometsproject D/SoLoader: Loaded: libfbjni.so
2021-11-24 18:10:23.206 4365-4388/com.awesometsproject D/SoLoader: About to load: libflipper.so
2021-11-24 18:10:23.206 4365-4388/com.awesometsproject D/SoLoader: libflipper.so not found on /data/data/com.awesometsproject/lib-main
2021-11-24 18:10:23.206 4365-4388/com.awesometsproject D/SoLoader: libflipper.so found on /data/app/com.awesometsproject-1/lib/x86
2021-11-24 18:10:23.206 4365-4388/com.awesometsproject D/SoLoader: Not resolving dependencies for libflipper.so
2021-11-24 18:10:23.236 4365-4388/com.awesometsproject D/SoLoader: Loaded: libflipper.so
2021-11-24 18:10:23.248 4365-4365/com.awesometsproject I/flipper: flipper: FlipperClient::addPlugin Inspector
2021-11-24 18:10:23.249 4365-4365/com.awesometsproject I/flipper: flipper: FlipperClient::addPlugin React
2021-11-24 18:10:23.249 4365-4365/com.awesometsproject I/flipper: flipper: FlipperClient::addPlugin Databases
2021-11-24 18:10:23.252 4365-4365/com.awesometsproject I/flipper: flipper: FlipperClient::addPlugin Preferences
2021-11-24 18:10:23.254 4365-4365/com.awesometsproject I/flipper: flipper: FlipperClient::addPlugin CrashReporter
2021-11-24 18:10:23.257 4365-4365/com.awesometsproject I/flipper: flipper: FlipperClient::addPlugin Network
2021-11-24 18:10:23.288 4365-4365/com.awesometsproject W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2021-11-24 18:10:23.348 4365-4365/com.awesometsproject W/unknown:ReactNative: Packager connection already open, nooping.
2021-11-24 18:10:23.444 4365-4403/com.awesometsproject I/OpenGLRenderer: Initialized EGL, version 1.4
2021-11-24 18:10:23.444 4365-4403/com.awesometsproject D/OpenGLRenderer: Swap behavior 1
2021-11-24 18:10:23.447 4365-4403/com.awesometsproject D/EGL_emulation: eglCreateContext: 0x9be2cf40: maj 2 min 0 rcv 2
2021-11-24 18:10:23.455 4365-4403/com.awesometsproject D/EGL_emulation: eglMakeCurrent: 0x9be2cf40: ver 2 0 (tinfo 0x99f06f90)
2021-11-24 18:10:23.591 4365-4403/com.awesometsproject D/EGL_emulation: eglMakeCurrent: 0x9be2cf40: ver 2 0 (tinfo 0x99f06f90)
2021-11-24 18:10:23.902 4365-4413/com.awesometsproject D/SoLoader: About to load: libreactnativejni.so
2021-11-24 18:10:23.902 4365-4413/com.awesometsproject D/SoLoader: libreactnativejni.so not found on /data/data/com.awesometsproject/lib-main
2021-11-24 18:10:23.902 4365-4413/com.awesometsproject D/SoLoader: libreactnativejni.so found on /data/app/com.awesometsproject-1/lib/x86
2021-11-24 18:10:23.902 4365-4413/com.awesometsproject D/SoLoader: Not resolving dependencies for libreactnativejni.so
2021-11-24 18:10:23.902 4365-4413/com.awesometsproject D/SoLoader: Loaded: libreactnativejni.so
2021-11-24 18:10:23.906 4365-4413/com.awesometsproject D/AppCenterCrashes: Setting react context
2021-11-24 18:10:23.907 4365-4413/com.awesometsproject D/AppCenterCrashes: Returning list containing crashes module
2021-11-24 18:10:23.923 4365-4365/com.awesometsproject W/unknown:ReactNative: Packager connection already open, nooping.
2021-11-24 18:10:23.966 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
2021-11-24 18:10:23.968 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
2021-11-24 18:10:23.971 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
2021-11-24 18:10:23.975 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
2021-11-24 18:10:23.975 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
2021-11-24 18:10:23.975 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
2021-11-24 18:10:23.976 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
2021-11-24 18:10:23.977 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
2021-11-24 18:10:23.978 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
2021-11-24 18:10:23.978 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
2021-11-24 18:10:23.979 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
2021-11-24 18:10:23.979 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
2021-11-24 18:10:23.982 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
2021-11-24 18:10:23.982 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
2021-11-24 18:10:23.983 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
2021-11-24 18:10:23.984 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
2021-11-24 18:10:23.984 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
2021-11-24 18:10:23.985 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
2021-11-24 18:10:23.989 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
2021-11-24 18:10:23.993 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
2021-11-24 18:10:23.995 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
2021-11-24 18:10:23.999 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
2021-11-24 18:10:24.000 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
2021-11-24 18:10:24.001 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
2021-11-24 18:10:24.002 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
2021-11-24 18:10:24.002 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
2021-11-24 18:10:24.002 4365-4415/com.awesometsproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.unimplementedview.ReactUnimplementedViewManager
2021-11-24 18:10:24.007 4365-4415/com.awesometsproject D/SoLoader: About to load: libyoga.so
2021-11-24 18:10:24.007 4365-4415/com.awesometsproject D/SoLoader: libyoga.so not found on /data/data/com.awesometsproject/lib-main
2021-11-24 18:10:24.007 4365-4415/com.awesometsproject D/SoLoader: libyoga.so found on /data/app/com.awesometsproject-1/lib/x86
2021-11-24 18:10:24.007 4365-4415/com.awesometsproject D/SoLoader: Not resolving dependencies for libyoga.so
2021-11-24 18:10:24.009 4365-4415/com.awesometsproject D/SoLoader: Loaded: libyoga.so
2021-11-24 18:10:24.027 4365-4415/com.awesometsproject I/flipper: flipper: FlipperClient::addPlugin Fresco
2021-11-24 18:10:24.155 4365-4414/com.awesometsproject D/SoLoader: About to load: libreactnativeblob.so
2021-11-24 18:10:24.155 4365-4414/com.awesometsproject D/SoLoader: libreactnativeblob.so not found on /data/data/com.awesometsproject/lib-main
2021-11-24 18:10:24.155 4365-4414/com.awesometsproject D/SoLoader: libreactnativeblob.so found on /data/app/com.awesometsproject-1/lib/x86
2021-11-24 18:10:24.155 4365-4414/com.awesometsproject D/SoLoader: Not resolving dependencies for libreactnativeblob.so
2021-11-24 18:10:24.155 4365-4414/com.awesometsproject D/SoLoader: Loaded: libreactnativeblob.so
2021-11-24 18:10:24.209 4365-4415/com.awesometsproject W/System: ClassLoader referenced unknown path: /system/app/Chrome/lib/x86
2021-11-24 18:10:24.213 4365-4415/com.awesometsproject D/ApplicationLoaders: ignored Vulkan layer search path /system/app/Chrome/lib/x86:/system/app/Chrome/Chrome.apk!/lib/x86:/system/lib:/vendor/lib for namespace 0xa9a69090
2021-11-24 18:10:24.214 4365-4415/com.awesometsproject I/WebViewFactory: Loading com.android.chrome version 69.0.3497.100 (code 349710017)
2021-11-24 18:10:24.244 4365-4414/com.awesometsproject W/ReactNativeJS: `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
2021-11-24 18:10:24.245 4365-4414/com.awesometsproject W/ReactNativeJS: `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art: Rejecting re-init on previously-failed class java.lang.Class<uJ>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/TracingController;
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:349)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at android.webkit.CookieManager com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager() (ForwardingCookieHandler.java:136)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.util.Map com.facebook.react.modules.network.ForwardingCookieHandler.get(java.net.URI, java.util.Map) (ForwardingCookieHandler.java:53)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.String com.facebook.react.modules.websocket.WebSocketModule.getCookie(java.lang.String) (WebSocketModule.java:392)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.modules.websocket.WebSocketModule.connect(java.lang.String, com.facebook.react.bridge.ReadableArray, com.facebook.react.bridge.ReadableMap, double) (WebSocketModule.java:100)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.JavaMethodWrapper.invoke(com.facebook.react.bridge.JSInstance, com.facebook.react.bridge.ReadableArray) (JavaMethodWrapper.java:372)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.JavaModuleWrapper.invoke(int, com.facebook.react.bridge.ReadableNativeArray) (JavaModuleWrapper.java:188)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.queue.NativeRunnable.run() (NativeRunnable.java:-2)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(android.os.Message) (MessageQueueThreadHandler.java:27)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void android.os.Looper.loop() (Looper.java:154)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run() (MessageQueueThreadImpl.java:226)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void java.lang.Thread.run() (Thread.java:761)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.TracingController" on path: DexPathList[[zip file "/system/app/Chrome/Chrome.apk"],nativeLibraryDirectories=[/system/app/Chrome/lib/x86, /system/app/Chrome/Chrome.apk!/lib/x86, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:349)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at android.webkit.CookieManager com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager() (ForwardingCookieHandler.java:136)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.util.Map com.facebook.react.modules.network.ForwardingCookieHandler.get(java.net.URI, java.util.Map) (ForwardingCookieHandler.java:53)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.String com.facebook.react.modules.websocket.WebSocketModule.getCookie(java.lang.String) (WebSocketModule.java:392)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.modules.websocket.WebSocketModule.connect(java.lang.String, com.facebook.react.bridge.ReadableArray, com.facebook.react.bridge.ReadableMap, double) (WebSocketModule.java:100)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.JavaMethodWrapper.invoke(com.facebook.react.bridge.JSInstance, com.facebook.react.bridge.ReadableArray) (JavaMethodWrapper.java:372)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.JavaModuleWrapper.invoke(int, com.facebook.react.bridge.ReadableNativeArray) (JavaModuleWrapper.java:188)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.queue.NativeRunnable.run() (NativeRunnable.java:-2)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(android.os.Message) (MessageQueueThreadHandler.java:27)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void android.os.Looper.loop() (Looper.java:154)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run() (MessageQueueThreadImpl.java:226)
2021-11-24 18:10:24.360 4365-4415/com.awesometsproject I/art:     at void java.lang.Thread.run() (Thread.java:761)
2021-11-24 18:10:24.380 4365-4415/com.awesometsproject I/cr_LibraryLoader: Time to load native libraries: 5 ms (timestamps 6304-6309)
2021-11-24 18:10:24.387 4365-4424/com.awesometsproject E/cr_VariationsUtils: Failed reading seed file "/data/user/0/com.awesometsproject/app_webview/variations_seed_new": /data/user/0/com.awesometsproject/app_webview/variations_seed_new (No such file or directory)
2021-11-24 18:10:24.390 4365-4415/com.awesometsproject I/chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
2021-11-24 18:10:24.391 4365-4415/com.awesometsproject I/cr_LibraryLoader: Expected native library version number "69.0.3497.100", actual native library version number "69.0.3497.100"
2021-11-24 18:10:24.439 4365-4414/com.awesometsproject I/ReactNativeJS: Running "AwesomeTSProject" with {"rootTag":1}
2021-11-24 18:10:24.522 4365-4368/com.awesometsproject I/art: Do partial code cache collection, code=30KB, data=27KB
2021-11-24 18:10:24.523 4365-4368/com.awesometsproject I/art: After code cache collection, code=28KB, data=26KB
2021-11-24 18:10:24.523 4365-4368/com.awesometsproject I/art: Increasing code cache capacity to 128KB
2021-11-24 18:10:24.615 4365-4380/com.awesometsproject I/AppCenterAnalytics: Analytics service has already been enabled.
2021-11-24 18:10:24.648 4365-4380/com.awesometsproject I/AppCenterCrashes: Crashes service has already been enabled.
2021-11-24 18:10:24.671 4365-4431/com.awesometsproject D/SoLoader: About to load: libimagepipeline.so
2021-11-24 18:10:24.671 4365-4431/com.awesometsproject D/SoLoader: libimagepipeline.so not found on /data/data/com.awesometsproject/lib-main
2021-11-24 18:10:24.675 4365-4431/com.awesometsproject D/SoLoader: libimagepipeline.so found on /data/app/com.awesometsproject-1/lib/x86
2021-11-24 18:10:24.675 4365-4431/com.awesometsproject D/SoLoader: Not resolving dependencies for libimagepipeline.so
2021-11-24 18:10:24.694 4365-4431/com.awesometsproject D/SoLoader: Loaded: libimagepipeline.so
2021-11-24 18:10:25.275 4365-4368/com.awesometsproject I/art: Do partial code cache collection, code=61KB, data=57KB
2021-11-24 18:10:25.275 4365-4368/com.awesometsproject I/art: After code cache collection, code=57KB, data=54KB
2021-11-24 18:10:25.275 4365-4368/com.awesometsproject I/art: Increasing code cache capacity to 256KB
2021-11-24 18:10:26.183 4365-4380/com.awesometsproject D/AppCenter: triggerIngestion(group_core) pendingLogCount=2
2021-11-24 18:10:26.183 4365-4380/com.awesometsproject D/AppCenter: Trying to get 2 logs from the Persistence database for group_core
2021-11-24 18:10:26.187 4365-4380/com.awesometsproject D/AppCenter: Returning 2 log(s) with an ID, efeddc97-ed35-4461-a4d3-7562e3642453
2021-11-24 18:10:26.187 4365-4380/com.awesometsproject D/AppCenter: The SID/ID pairs for returning log(s) is/are:
2021-11-24 18:10:26.187 4365-4380/com.awesometsproject D/AppCenter: 	null / 33
2021-11-24 18:10:26.187 4365-4380/com.awesometsproject D/AppCenter: 	null / 34
2021-11-24 18:10:26.187 4365-4380/com.awesometsproject D/AppCenter: ingestLogs(group_core,efeddc97-ed35-4461-a4d3-7562e3642453) pendingLogCount=0
2021-11-24 18:10:26.192 4365-4380/com.awesometsproject D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2021-11-24 18:10:26.193 4365-4386/com.awesometsproject V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2021-11-24 18:10:26.193 4365-4386/com.awesometsproject V/AppCenter: Headers: {Install-ID=46b246a5-4cf0-4b72-8a63-0838609570d3, App-Secret=****************************a9c57377, Content-Type=application/json}
2021-11-24 18:10:26.193 4365-4386/com.awesometsproject V/AppCenter: {
      "logs": [
        {
          "type": "startService",
          "timestamp": "2021-11-24T16:10:23.169Z",
          "device": {
            "wrapperSdkVersion": "4.3.1",
            "wrapperSdkName": "appcenter.react-native",
            "sdkName": "appcenter.android",
            "sdkVersion": "4.3.1",
            "model": "Android SDK built for x86",
            "oemName": "Google",
            "osName": "Android",
            "osVersion": "7.1.1",
            "osBuild": "NYC",
            "osApiLevel": 25,
            "locale": "en_US",
            "timeZoneOffset": 120,
            "screenSize": "1440x2392",
            "appVersion": "1.0",
            "carrierName": "Android",
            "carrierCountry": "us",
            "appBuild": "1",
            "appNamespace": "com.awesometsproject"
          },
          "services": [
            "Analytics"
          ]
        },
        {
          "type": "startService",
          "timestamp": "2021-11-24T16:10:23.185Z",
          "device": {
            "wrapperSdkVersion": "4.3.1",
            "wrapperSdkName": "appcenter.react-native",
            "sdkName": "appcenter.android",
            "sdkVersion": "4.3.1",
            "model": "Android SDK built for x86",
            "oemName": "Google",
            "osName": "Android",
            "osVersion": "7.1.1",
            "osBuild": "NYC",
            "osApiLevel": 25,
            "locale": "en_US",
            "timeZoneOffset": 120,
            "screenSize": "1440x2392",
            "appVersion": "1.0",
            "carrierName": "Android",
            "carrierCountry": "us",
            "appBuild": "1",
            "appNamespace": "com.awesometsproject"
          },
          "services": [
            "Crashes"
          ]
        }
      ]
    }
2021-11-24 18:10:26.326 4365-4380/com.awesometsproject D/AppCenter: triggerIngestion(group_analytics) pendingLogCount=1
2021-11-24 18:10:26.326 4365-4380/com.awesometsproject D/AppCenter: Trying to get 1 logs from the Persistence database for group_analytics
2021-11-24 18:10:26.327 4365-4380/com.awesometsproject D/AppCenter: Returning 1 log(s) with an ID, d3e8f395-c9dc-4551-a3f1-a08233429667
2021-11-24 18:10:26.327 4365-4380/com.awesometsproject D/AppCenter: The SID/ID pairs for returning log(s) is/are:
2021-11-24 18:10:26.327 4365-4380/com.awesometsproject D/AppCenter: 	8e688b1f-3c4f-420f-9614-7b9590422766 / 35
2021-11-24 18:10:26.327 4365-4380/com.awesometsproject D/AppCenter: ingestLogs(group_analytics,d3e8f395-c9dc-4551-a3f1-a08233429667) pendingLogCount=0
2021-11-24 18:10:26.328 4365-4380/com.awesometsproject D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=3000
2021-11-24 18:10:26.332 4365-4385/com.awesometsproject V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2021-11-24 18:10:26.332 4365-4385/com.awesometsproject V/AppCenter: Headers: {Install-ID=46b246a5-4cf0-4b72-8a63-0838609570d3, App-Secret=****************************a9c57377, Content-Type=application/json}
2021-11-24 18:10:26.332 4365-4385/com.awesometsproject V/AppCenter: {
      "logs": [
        {
          "type": "startSession",
          "timestamp": "2021-11-24T16:10:23.315Z",
          "sid": "8e688b1f-3c4f-420f-9614-7b9590422766",
          "device": {
            "wrapperSdkVersion": "4.3.1",
            "wrapperSdkName": "appcenter.react-native",
            "sdkName": "appcenter.android",
            "sdkVersion": "4.3.1",
            "model": "Android SDK built for x86",
            "oemName": "Google",
            "osName": "Android",
            "osVersion": "7.1.1",
            "osBuild": "NYC",
            "osApiLevel": 25,
            "locale": "en_US",
            "timeZoneOffset": 120,
            "screenSize": "1440x2392",
            "appVersion": "1.0",
            "carrierName": "Android",
            "carrierCountry": "us",
            "appBuild": "1",
            "appNamespace": "com.awesometsproject"
          }
        }
      ]
    }
2021-11-24 18:10:26.761 4365-4385/com.awesometsproject V/AppCenter: HTTP response status=200 payload={"status":"Success","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"d70d2ff5-875d-4ed8-a13d-0315435981c7"}
2021-11-24 18:10:26.762 4365-4380/com.awesometsproject D/AppCenter: Deleting logs from the Persistence database for group_analytics with d3e8f395-c9dc-4551-a3f1-a08233429667
2021-11-24 18:10:26.762 4365-4380/com.awesometsproject D/AppCenter: The IDs for deleting log(s) is/are:
2021-11-24 18:10:26.762 4365-4380/com.awesometsproject D/AppCenter: 	35
2021-11-24 18:10:26.766 4365-4380/com.awesometsproject D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=3000
2021-11-24 18:10:30.452 4365-4386/com.awesometsproject V/AppCenter: HTTP response status=200 payload={"status":"Success","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"e05f8dc3-85b9-4e03-9b04-02bc2eb0a9fe"}
2021-11-24 18:10:30.453 4365-4380/com.awesometsproject D/AppCenter: Deleting logs from the Persistence database for group_core with efeddc97-ed35-4461-a4d3-7562e3642453
2021-11-24 18:10:30.453 4365-4380/com.awesometsproject D/AppCenter: The IDs for deleting log(s) is/are:
2021-11-24 18:10:30.453 4365-4380/com.awesometsproject D/AppCenter: 	33
2021-11-24 18:10:30.457 4365-4380/com.awesometsproject D/AppCenter: 	34
2021-11-24 18:10:30.459 4365-4380/com.awesometsproject D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2021-11-24 18:10:34.584 4365-4380/com.awesometsproject D/AppCenter: Storing a log to the Persistence database for log type event with flags=1
2021-11-24 18:10:34.592 4365-4380/com.awesometsproject D/AppCenter: Stored a log to the Persistence database for log type event with databaseId=36
2021-11-24 18:10:34.592 4365-4380/com.awesometsproject D/AppCenter: enqueue(group_analytics) pendingLogCount=1
2021-11-24 18:10:34.592 4365-4380/com.awesometsproject D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=1 batchTimeInterval=3000
2021-11-24 18:10:34.759 4365-4403/com.awesometsproject D/EGL_emulation: eglMakeCurrent: 0x9be2cf40: ver 2 0 (tinfo 0x99f06f90)
2021-11-24 18:10:34.863 4365-4403/com.awesometsproject D/EGL_emulation: eglMakeCurrent: 0x9be2cf40: ver 2 0 (tinfo 0x99f06f90)
2021-11-24 18:10:34.932 4365-4403/com.awesometsproject D/EGL_emulation: eglMakeCurrent: 0x9be2cf40: ver 2 0 (tinfo 0x99f06f90)
2021-11-24 18:10:34.949 4365-4403/com.awesometsproject D/EGL_emulation: eglMakeCurrent: 0x9be2cf40: ver 2 0 (tinfo 0x99f06f90)
2021-11-24 18:10:36.240 4365-4403/com.awesometsproject D/EGL_emulation: eglMakeCurrent: 0x9be2cf40: ver 2 0 (tinfo 0x99f06f90)
2021-11-24 18:10:36.457 4365-4403/com.awesometsproject D/EGL_emulation: eglMakeCurrent: 0x9be2cf40: ver 2 0 (tinfo 0x99f06f90)
2021-11-24 18:10:36.460 4365-4403/com.awesometsproject D/OpenGLRenderer: endAllActiveAnimators on 0x87526680 (RippleDrawable) with handle 0x87b9e920
2021-11-24 18:10:37.597 4365-4380/com.awesometsproject D/AppCenter: triggerIngestion(group_analytics) pendingLogCount=1
2021-11-24 18:10:37.598 4365-4380/com.awesometsproject D/AppCenter: Trying to get 1 logs from the Persistence database for group_analytics
2021-11-24 18:10:37.598 4365-4380/com.awesometsproject D/AppCenter: Returning 1 log(s) with an ID, adec7d58-fcd7-4cb4-a780-c53c1971d000
2021-11-24 18:10:37.598 4365-4380/com.awesometsproject D/AppCenter: The SID/ID pairs for returning log(s) is/are:
2021-11-24 18:10:37.598 4365-4380/com.awesometsproject D/AppCenter: 	8e688b1f-3c4f-420f-9614-7b9590422766 / 36
2021-11-24 18:10:37.598 4365-4380/com.awesometsproject D/AppCenter: ingestLogs(group_analytics,adec7d58-fcd7-4cb4-a780-c53c1971d000) pendingLogCount=0
2021-11-24 18:10:37.598 4365-4380/com.awesometsproject D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=3000
2021-11-24 18:10:37.599 4365-4385/com.awesometsproject V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2021-11-24 18:10:37.599 4365-4385/com.awesometsproject V/AppCenter: Headers: {Install-ID=46b246a5-4cf0-4b72-8a63-0838609570d3, App-Secret=****************************a9c57377, Content-Type=application/json}
2021-11-24 18:10:37.599 4365-4385/com.awesometsproject V/AppCenter: {
      "logs": [
        {
          "type": "event",
          "timestamp": "2021-11-24T16:10:34.584Z",
          "sid": "8e688b1f-3c4f-420f-9614-7b9590422766",
          "device": {
            "wrapperSdkVersion": "4.3.1",
            "wrapperSdkName": "appcenter.react-native",
            "sdkName": "appcenter.android",
            "sdkVersion": "4.3.1",
            "model": "Android SDK built for x86",
            "oemName": "Google",
            "osName": "Android",
            "osVersion": "7.1.1",
            "osBuild": "NYC",
            "osApiLevel": 25,
            "locale": "en_US",
            "timeZoneOffset": 120,
            "screenSize": "1440x2392",
            "appVersion": "1.0",
            "carrierName": "Android",
            "carrierCountry": "us",
            "appBuild": "1",
            "appNamespace": "com.awesometsproject"
          },
          "name": "button clicked...",
          "id": "d055c1d4-b6f3-4100-8689-e9848dc8d6db",
          "typedProperties": [
            {
              "type": "string",
              "name": "timestamp",
              "value": "2021-11-24T16:10:34.582Z"
            }
          ]
        }
      ]
    }
2021-11-24 18:10:37.847 4365-4385/com.awesometsproject V/AppCenter: HTTP response status=200 payload={"status":"Success","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"68abf9ef-38c8-4059-b926-404c3e4267a2"}
2021-11-24 18:10:37.847 4365-4380/com.awesometsproject D/AppCenter: Deleting logs from the Persistence database for group_analytics with adec7d58-fcd7-4cb4-a780-c53c1971d000
2021-11-24 18:10:37.847 4365-4380/com.awesometsproject D/AppCenter: The IDs for deleting log(s) is/are:
2021-11-24 18:10:37.847 4365-4380/com.awesometsproject D/AppCenter: 	36
2021-11-24 18:10:37.851 4365-4380/com.awesometsproject D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=3000
```

**Comment by AnatolyPristensky** [comment]
Hello, @nkoudelia,
This is likely due to the newest version of react-native. Here are some examples of the similar warnings (or errors in some case): 
https://github.com/react-navigation/react-navigation/issues/9882
https://github.com/react-native-netinfo/react-native-netinfo/issues/486
https://github.com/software-mansion/react-native-reanimated/issues/2297

We created a bug for this issue on our internal dashboard and will fix it. 
As a workaround, you can hide the warning for now:

```
import { LogBox } from 'react-native';
LogBox.ignoreLogs(['new NativeEventEmitter']); // Ignore log notification by message
LogBox.ignoreAllLogs(); //Ignore all log notifications
```

**Comment by AnatolyPristensky** [comment]
Fixed in [release 4.4.3](https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/4.4.3)

**Comment by nkoudelia** [comment]
Hi @AnatolyPristensky!

I'm still seeing the warnings:

![image](https://user-images.githubusercontent.com/91388229/150934589-337df878-99dc-4cb7-b533-f9aa8a05be54.png)

![image](https://user-images.githubusercontent.com/91388229/150934871-7d9b22cb-0965-4ff8-8118-7b8953935d74.png)

**Comment by AnatolyPristensky** [comment]
Hello @nkoudelia 
You are correct. I'm able to reproduce this issue on 4.4.3. 
We will investigate it and update you with the status once get results.

**Comment by DmitriyKirakosyan** [comment]
Hi @nkoudelia , unfortunately we don't have capacity for this issue, so it is not going to be fixed soon.
However, contribution is always very welcome :)

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
